### ISSUE TITLE
UnsupportedAxiomTypeException: Unsupported type of axiom: EquivalentClasses

### ISSUE THREAD

**Issue by Chuhtra** [ignazio1977/owlexplanation#6]
Hi Ignazio,

I am facing this issue which I can't figure out. Is the EquivalentClassAxiom supported by owlexplanation 5.0.0?

I get `org.semanticweb.owl.explanation.impl.blackbox.checker.SatisfiabilityEntailmentChecker$UnsupportedAxiomTypeException: Unsupported type of axiom: EquivalentClasses` 

for the axiom `EquivalentClasses(<http://stelios.org/onto.owl#Dog> <http://stelios.org/onto.owl#Rough> <http://stelios.org/onto.owl#Young>)`, of [this](https://github.com/ignazio1977/owlexplanation/files/8235133/ONTO_ASRTD_a_qun7yw.txt) ontology.

Keep in mind the ontology is randomly generated so don't bother making sense of any meaning in it.

I am using HermiT 1.4.5.519, OWLAPI 5.1.19 and Owlexplanation 5.0.0.

Thank you for your work.

**Comment by ignazio1977** [comment]
The code throwing the exception is this:

        public OWLClassExpression visit(OWLEquivalentClassesAxiom ax) {
            List<OWLClassExpression> expressions=asList(ax.classExpressions());
            if (expressions.size() != 2) {
                throw new UnsupportedAxiomTypeException(ax);
            }


OWLEquivalentClassesAxiom is supported for cardinality = 2 - looks to be because how the equivalent classes are used in the rest of the method.

Possible workaround: split the axiom in pairwise axioms and collect the results; as a set of pairwise axioms and a single equivalent axiom are semantically equivalent, this might do what you need.

    OWLEquivalentClassesAxiom ax = df.getOWLEquivalentClassesAxiom(
        df.getOWLClass("http://stelios.org/onto.owl#Dog"),
        df.getOWLClass("http://stelios.org/onto.owl#Rough"),
        df.getOWLClass("http://stelios.org/onto.owl#Young"));
    ax.asPairwiseAxioms().forEach(a->{
    SatisfiabilityEntailmentChecker c=new SatisfiabilityEntailmentChecker(rf, a, OWLManager::createOWLOntologyManager);
    System.out.println("TestExplanation.main() " +c.getEntailingAxioms(new HashSet<>(Arrays.asList(ax))));
    });

**Comment by Chuhtra** [comment]
Yes, that is the case, thank you! Although, while [here](https://javadoc.io/static/net.sourceforge.owlapi/owlapi-distribution/5.1.19/org/semanticweb/owlapi/model/OWLNaryAxiom.html#asPairwiseAxioms--) says that the 3 pairs are returned, I only get two (namely Dog-Rough and Rough-Young). Do you know why the third one (Dog-Young) is not returned?

EDIT: Also, if you agree, I would suggest a more descriptive error when the `UnsupportedAxiomTypeException` is thrown, stating the requirement of at most 2 entities present.

**Comment by ignazio1977** [comment]
It's a documentation bug. `asPairwiseAxioms()` is supposed to have the same behaviour and description as `splitToAnnotatedPairs()`, the difference being the presence of annotations in the pairwise axioms.

The behaviour used to be to return all pairs, but that was an error - because of transitivity, n-1 axioms are sufficient to represent an equivalent axiom with n operands. Returning all pairs requires n^2/2 - 1 axioms instead, which, for large equivalences (or disjoint/sameAs/differentFrom axioms), increases the size of output and the amount of memory required unnecessarily. Also, reasoners are supposed to absorb such axioms to reduce the impact on tableaux, but the difference in performance in carrying out this task was significant for some reasoners - so reducing the number of unnecessary axioms was a gain all around. But it's hard to keep the documentation in sync.

Agreed, the error message could be better.

**Comment by Chuhtra** [comment]
I see. Thank you for your insight and your detailed explanation!
